# Creates a mysql database and wildfly instance
# Usage: docker-compose up
version: '2.0'
services:
  tradie_db:
    container_name: tradie_mysql_db
    image: 'mysql'
    ports:
      - '3307:3306'
    expose:
      - '3306'
    environment:
      MYSQL_ROOT_PASSWORD: 'sa'
      MYSQL_DATABASE: 'tradie'
      MYSQL_USER: 'sa'
      MYSQL_PASSWORD: 'sa'
  tradie_wildfly:
    container_name: tradie_wildfly_mysql
    image: 'bizhubaustralia/skyve-wildfly-mysql::latest'
    ports:
      - '8081:8080'
      - '9991:9990'
      - '8788:8787'
    environment:
      SKYVE_CONTENT: '/content/'
      SKYVE_DATASTORE_DIALECT: 'org.skyve.impl.persistence.hibernate.dialect.MySQL8InnoDBSpatialDialect'
      SKYVE_HOSTNAME: 'localhost'
      SKYVE_PORT: '8081'
      SKYVE_URL: 'http://localhost:8081'
      DATABASE_URL: 'tradie_db'
      DATABASE_PORT: '3306'
      SKYVE_SECURITY_DOMAIN_NAME: 'tradie'
      SKYVE_JNDI_NAME: 'tradieDB'
      IDENTIFIER: 'DEV'
    volumes:
      - '../../deployments:/opt/jboss/wildfly/standalone/deployments/'
      - './content:/content'
